### ISSUE TITLE
Refactor doesn't work with Vue files and typescript

### ISSUE THREAD

**Issue by webcoderkz** [cmstead/js-refactor#100]
Code example:

```
@Component
class Example extends Vue {
  public mounted(): void {
    console.log('test')
  }
}
```

When i select `console.log('test')` line, then press Shift + ⌘ + J + V and i'm getting an error: "Unable to parse source code. Parser error: Unexpected character '@'" and "Running the contributed command: 'cmstead.jsRefactor.extractVariable' failed."

**Comment by cmstead** [comment]
Hm. I'll investigate this. This might be a problem with the way that the TypeScript parser I am using actually works. I'll Let you know. : /

**Comment by cmstead** [comment]
JS Refactor is no longer supported because I created a ground-up replacement. I test-ran this case and it appears to be working correctly. YAY!

Please have a look:

GitHub (latest build):

https://github.com/cmstead/js-codeformer/releases

VS Marketplace:

https://marketplace.visualstudio.com/items?itemName=cmstead.js-codeformer
