### ISSUE TITLE
Convert to Arrow Function with optional chaining problem

### ISSUE THREAD

**Issue by etiennejcharles** [cmstead/js-refactor#103]
When I have a function with optional chaining below the function I'm trying to refactor, it doesn't work 😢 

![some-optional-chainning](https://user-images.githubusercontent.com/2872476/69155234-55027380-0aaf-11ea-9b3c-fad7db0750a6.gif)

**Comment by cmstead** [comment]
I'm going to test and see if I can update the parser library I use. It is likely related to optional chaining being a very new language feature.

**Comment by cmstead** [comment]
I updated to the latest parser version and still no luck. Perhaps it will be available soon. I'm sorry about that. :-(

**Comment by cmstead** [comment]
I'm really sorry for taking so long to reply. I am closing up shop on JSR, BECAUSE there is a replacement tool. It's still under construction, but it should resolve the issue you are running into.

Marketplace:

https://marketplace.visualstudio.com/items?itemName=cmstead.js-codeformer

GitHub:

https://github.com/cmstead/js-codeformer
