### ISSUE TITLE
Converting async function to arrow function removes async

### ISSUE THREAD

**Issue by BigsonLvrocha** [cmstead/js-refactor#105]
```typescript
async function foo() {
  const data = await Promise.resolve('bar');
  return data;
}
```
will convert to
```typescript
const foo = () => {
  const data = await Promise.resolve('bar');
  return data;
};
```
should be 
```typescript
const foo = async () => {
  const data = await Promise.resolve('bar');
  return data;
};
```

**Comment by DavidSampson** [comment]
The same happens in reverse:

```javascript
async () => { await myPromise() }
```
becomes
```javascript
function(){
  return await myPromise();
}
```

**Comment by cmstead** [comment]
Crud. I'll have a look. Thank you!

**Comment by cmstead** [comment]
Sorry for the long delay in response. I have stopped supporting JSR because I am replacing it with a new tool. This fix is in the latest tagged release on GitHub and will be published later this evening or tomorrow!

Release:

https://github.com/cmstead/js-codeformer/releases/tag/v0.13.5

JS CodeFormer on GitHub:

https://github.com/cmstead/js-codeformer

JS CodeFormer on the VS Marketplace:

https://marketplace.visualstudio.com/items?itemName=cmstead.js-codeformer
