### ISSUE TITLE
Cannot export a class

### ISSUE THREAD

**Issue by OmgImAlexis** [cmstead/js-refactor#107]
I'm getting this error while trying to export a class. Is there a reason only variables and functions are supported?

```
Cannot export a value which is not a function or variable declaration.
```

**Comment by cmstead** [comment]
Hi, sorry for the delay. I will have to look into supporting class export. This is a case I hadn't considered, so I'll need to do a little research to make it work.

**Comment by cmstead** [comment]
I'm really sorry for taking so long to reply. I am closing up shop on JSR, BECAUSE there is a replacement tool. It's still under construction, but it should resolve the issue you are running into.

Marketplace:

https://marketplace.visualstudio.com/items?itemName=cmstead.js-codeformer

GitHub:

https://github.com/cmstead/js-codeformer
