### ISSUE TITLE
Is extension not working with React?

### ISSUE THREAD

**Issue by exocode** [cmstead/js-refactor#110]
I have issues using your extension:

- No acceptable function found which can be converted to arrow function.
```
import React from 'react';
function profile() {} /// <--- This is marked while using js-refactor
```

- Unable to parse source code. Parser error: Unexpected token <
```
// the following is marked
function profile() {
  return (
    <div>
    </div>
  )
}
```
This also wont work
- Unable to parse source code. Parser error: Unexpected token )
```
function profile() {
  return (
  )
}
```

**Comment by cmstead** [comment]
React support is still experimental. I am in the process of improving some of the code so I can better support issues, but once I get that work in place I will dig into react support issues and improve the experience.

**Comment by TonyGravagno** [comment]
Please confirm if the anomaly I'm seeing is related to React support. I have a test React project, and the following in App.js:
```js
function App() {
  return (
    <div className="contact-card">
    <img src="https://via.placeholder.com/150" alt="Profile" />
```
My goal is to select literals from in the `img` tag and extract them to variables. That is, for this simple test, I'd like the result to be:
```js
function App() {
  const imagePlaceholderURI="https://via.placeholder.com/100";
  const imagePlaceholderAlt="Card";
  return (
    <div className="contact-card">
    <img src={imagePlaceholderURI} alt={imagePlaceholderAlt} />
```
The refactoring menu shows the extraction options for this extension but they are disabled.
Any suggested workaround?
Thanks!

**Comment by TonyGravagno** [comment]
Follow-up for now : I just found that the [Abracadabra extension](https://github.com/nicoespeon/abracadabra) does support this functionality.

**Comment by cmstead** [comment]
I'm really sorry for taking so long to reply. I am closing up shop on JSR, BECAUSE there is a replacement tool. It's still under construction, but it should resolve the issue you are running into.

I haven't tried things with React just yet, but I believe you should get what you need out of the box. I'll research more.

As an aside, I spoke with Carlo, and it looks like Abracadabra is going dormant since he has a number of priorities he needs to attend to. I'm hoping to support his userbase with CodeFormer as well.

Marketplace:

https://marketplace.visualstudio.com/items?itemName=cmstead.js-codeformer

GitHub:

https://github.com/cmstead/js-codeformer
