### ISSUE TITLE
Svelte support

### ISSUE THREAD

**Issue by PlkMarudny** [cmstead/js-refactor#112]
May I suggest adding support for [Svelte](https://svelte.dev/)? Technically, it is quite similar to Vue, but easier.

**Comment by cmstead** [comment]
I'll take a look. 👍

**Comment by cmstead** [comment]
JSR is no longer supported because I started building a replacement, from the ground-up. It appears refactorings work in Svelte alright, though any renaming that happens which affects properties used in the HTML will not propagate into the HTML itself. Otherwise, everything seems to work normally from some preliminary testing. Give it a go. :-)

GitHub:

https://github.com/cmstead/js-codeformer/releases/tag/v0.16.0

Visual Studio Marketplace:

https://marketplace.visualstudio.com/items?itemName=cmstead.js-codeformer
