### ISSUE TITLE
Publish extensions to open-vsx

### ISSUE THREAD

**Issue by orblazer** [cmstead/js-refactor#115]
I'm a [VS Codium](https://github.com/VSCodium/vscodium) user, a FLOSS version of VS Code, it's the same code but without the Microsoft's telemetry and branding.
I want to request if possible to add the _JS Refactor_ extension on the [open-vsx.org](https://open-vsx.org/) market to us doesn't need to works with the Microsoft marketplace as is unclear if it's legal to use it on VS Code forks, see [here](https://github.com/microsoft/vscode/issues/31168).

Additional info:

- This is [how to](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) publish a new extension.

**Comment by cmstead** [comment]
Hi, I'll have a look. I won't be doing any new work on JSR because I have been building a replacement I'll keep this issue open until I can either do the work with the new project, or close it if it's something I'm not going to be able to support.

Here's some further information:

Marketplace:

https://marketplace.visualstudio.com/items?itemName=cmstead.js-codeformer

GitHub:

https://github.com/cmstead/js-codeformer

**Comment by cmstead** [comment]
If VS Codium can install VSIX files, you can install the nightly for the time being. You can find all nightly builds under releases.

**Comment by cmstead** [comment]
Though I appreciate the effort going into a separate open extension repository, I don't think I have the bandwidth to keep up with the extra publishing load.
