### ISSUE TITLE
miss a $ sign after refactoring when naming start with $$

### ISSUE THREAD

**Issue by chenxiaoyao6228** [cmstead/js-refactor#116]
Great thanks for the authors' great work, but I encounted some issues when using `js-refactor`

When variables  or function names start with `$$` sign 

```js
function $$a() {
  return 'aa'
}
```
after refatoring, it always missed one `$` sign
```js
const $a = () => 'aa'
```

**Comment by cmstead** [comment]
I'm sorry this has been sitting for so long. I'm not longer supporting JSR, because I have a new tool which replaces it. I believe your issue should be resolved in the new tool. Please consider giving it a try:

VS Marketplace:

https://marketplace.visualstudio.com/items?itemName=cmstead.js-codeformer

GitHub: https://github.com/cmstead/js-codeformer
