### ISSUE TITLE
Extract method fails

### ISSUE THREAD

**Issue by erikwett** [cmstead/js-refactor#117]
When I try 'Extract method' I get the error:
Unable to parse source code. Parser error: Unexpected token {

Pretty strange, there is no { in the code I selected.

**Comment by cmstead** [comment]
I'm really sorry for taking so long to reply. I am closing up shop on JSR, BECAUSE there is a replacement tool. It's still under construction, but it should resolve the issue you are running into.

Marketplace:

https://marketplace.visualstudio.com/items?itemName=cmstead.js-codeformer

GitHub:

https://github.com/cmstead/js-codeformer
