### ISSUE TITLE
"Unable to parse source code" when using Babel JavaScript

### ISSUE THREAD

**Issue by kud** [cmstead/js-refactor#118]
Hello!

When I use the syntax "Babel JavaScript" (https://marketplace.visualstudio.com/items?itemName=mgmcdermott.vscode-language-babel), I always got this error: `Unable to parse source code`

Is there a way to fix it?

When I switch to `JavaScript React`, it works but it's not a solution for me.

Thank you!

**Comment by kud** [comment]
No news? :(

**Comment by cmstead** [comment]
I'm really sorry for taking so long to reply. I am closing up shop on JSR, BECAUSE there is a replacement tool. It's still under construction, but it should resolve the issue you are running into.

Marketplace:

https://marketplace.visualstudio.com/items?itemName=cmstead.js-codeformer

GitHub:

https://github.com/cmstead/js-codeformer
