### ISSUE TITLE
Inline variable: Unable to parse source code. Parser error: Unexpected token import

### ISSUE THREAD

**Issue by martixy** [cmstead/js-refactor#120]
I tried to inline the following variable:
`const UserProfile = () => import('@/views/dashboard/pages/UserProfile')`

And received this error:
`Unable to parse source code. Parser error: Unexpected token import`

**Comment by cmstead** [comment]
I'm really sorry for taking so long to reply. I am closing up shop on JSR, BECAUSE there is a replacement tool. It's still under construction, but it should resolve the issue you are running into.

Marketplace:

https://marketplace.visualstudio.com/items?itemName=cmstead.js-codeformer

GitHub:

https://github.com/cmstead/js-codeformer
