### ISSUE TITLE
Cannot get this to do anything at all

### ISSUE THREAD

**Issue by wardyment** [cmstead/js-refactor#123]
Installed extension.
Opened JS file.
Right click choose from one of the JS Refactor menu items.
Nothing happens.
Tried different JS files and different methods.
No joy.
JS Refactor 2.20.6
VS Code: 1.56.2
Windows 10

**Comment by cmstead** [comment]
I'm really sorry for taking so long to reply. I am closing up shop on JSR, BECAUSE there is a replacement tool. It's still under construction, but it should resolve the issue you are running into.

Marketplace:

https://marketplace.visualstudio.com/items?itemName=cmstead.js-codeformer

GitHub:

https://github.com/cmstead/js-codeformer
