### ISSUE TITLE
Introduce function

### ISSUE THREAD

**Issue by dibikhin** [cmstead/js-refactor#21]
Select a text, hit 'introduce function', new function created with name as the selected text.

Having this:

```
var foo = {
    bar: quux
};
```

Selecting `quux` and hitting `introduce function` should lead to:

```
function quux() {
    <cursor>
}
var foo = {
    bar: quux
};
```

**Comment by cmstead** [comment]
Seems like a reasonable idea. I'll add it to the list and see what I can do. : )

**Comment by dibikhin** [comment]
Cool ;)

**Comment by dibikhin** [comment]
Found a similar case. Selecting `bar` or `bar()` and hitting 'introduce function' here:

    var foo = bar();

should add new named function `bar`:

    function bar() {
    <cursor>
    }
    var foo = bar();

And it should work with params too:

    var foo = bar(qux, baz);

'introduce function' -->

    function bar(qux, baz) {
    <cursor>
    }
    var foo = bar(qux, baz);

**Comment by dibikhin** [comment]
@cmstead I see an algo for this in this way: if a selection contains a function call (like `blabla()`) then extract the function's name and insert a new function using that name somewhere; if the selection doesn't contain a function call then show an error.

Could you point me to a code that chooses a position for a new code insertion?

**Comment by cmstead** [comment]
It turns out there is no specific piece of code that picks a position. If
you look through the code for extracting a variable, you'll see I'm using
esprima to generate a token set and then using a pushdown automaton to
identify function scope.

My current goal when I have a little time is to get better test coverage
and refactor some of the code so I might be able to simplify the process.
:-/

**Comment by dibikhin** [comment]
Ok. Thx.
Also, I'll check existing tests for coverage and new cases.
How do you measure a test coverage?

**Comment by cmstead** [comment]
Currently I think I'm not. It's on the list after I get the code to a more
testable place.

**Comment by dibikhin** [comment]
I could introduce coverage with `Istanbul` this week. It takes just a few seconds and we'll be able to see test coverage as a surfable HTML file.

You can try it so: clone my [Express boilerplate](https://github.com/dibikhin/expressjs-template) and run `npm install && npm run cover`.

**Comment by cmstead** [comment]
I appreciate it, but I'd really like to handle that when I dig back in. I'm
more concerned with abstracting the vscode module first since no files can
be imported when they refer to vscode given the way that particular module
works. I appreciate the offer nonetheless.
On Apr 18, 2016 8:12 AM, "Roman Dibikhin" <notifications@github.com> wrote:

I could introduce coverage with Istanbul this week. It takes just a few
seconds and we'll be able to see test coverage as a surfable HTML file.

You can try it so: clone my Express boilerplate
<https://github.com/dibikhin/expressjs-template> and run npm install && npm
run cover.

—
You are receiving this because you were mentioned.

Reply to this email directly or view it on GitHub
<https://github.com/cmstead/js-refactor/issues/21#issuecomment-211423594>

**Comment by dibikhin** [comment]
Ok, sure.

How can I contribute?

**Comment by cmstead** [comment]
I'm going to do some tests this week. Once I have that ready to go, I think I will be ready for help on this. Sorry I've been a little slow. It's been tough trying to keep up with everything,

**Comment by dibikhin** [comment]
No problem. I'm busy too.

**Comment by cmstead** [comment]
Okay, I got the vscodeFactory in place and added approval testing. You can take a look at the way I stubbed the vscode module in extension.test.js.  Be sure to install Beyond Compare before you run the tests if you modify the actions or your new action won't approve properly.  Let me know if/when you have questions and I'll do my best to help out. : )

Oh, BTW, thanks for the help!

**Comment by cmstead** [comment]
I have some example test code in place and ready to go. Take a look at the add-export command code for examples on how to test command code.

**Comment by cmstead** [comment]
Okay, I know this has been a long time coming, but I have pushed 2.8.1 with introduce function.  I haven't sorted out placing the cursor inside the new function, but I will as soon as I can.

https://marketplace.visualstudio.com/items?itemName=cmstead.jsrefactor
