### ISSUE TITLE
Multi-Selection

### ISSUE THREAD

**Issue by con-ssc** [cmstead/js-refactor#29]
It would be nice if convert operations would work with multi-selection.

**Comment by cmstead** [comment]
I am just about to dive into retooling much of this package, so I will take a look at this as I get things wrapped in tests and working a little more reliably. Sorry for the long delay!

**Comment by cmstead** [comment]
I'm starting to examine edge cases. Here are the ones I am most concerned with:

- If someone selects multiple functions in a single selection, how do I deal with this?

- If one (or more) function does not pass the requirements for the refactoring, I'm not sure how I would alert the user to the failure and be specific since I feel like changing the user selection is a really bad thing and popping up multiple error messages when multiple functions are bad is kind of hinky.

Ultimately, I am erring on the side of caution until I can figure out a way to reconcile these concerns.

**Comment by cmstead** [comment]
Right now it looks like this behavior might be beyond the strength of a mere mortal like myself. There is a lot of source management that I would have to do and I'm not sure if I have it in me to make this happen right now. I'll revisit multi-select behaviors in the future. : /
