### ISSUE TITLE
Extract variable not working inside arrow functions

### ISSUE THREAD

**Issue by andys8** [cmstead/js-refactor#38]
Hi, this extensions looks great.

I found an issue when I was trying to extract a value to a variable. It's working with ES5 functions, but not with arrow functions.

#### How to reproduce
Extracting the string `'param'` to a variable won't work in this example.
```js
const arrorFunc = (input) => {
  this.arrowFunc('param');
};
```
You'll get:
![image](https://cloud.githubusercontent.com/assets/13085980/25291080/e91a0cf6-26d0-11e7-8516-ed633178ab4e.png)

**Comment by cmstead** [comment]
I knew this issue would eventually arise. I've been trying to figure out the best way to solve this. Walking the AST is kind of messy and the tokens for the source don't contain useful identifiers.  I'm open to ideas if anyone has one.

**Comment by andys8** [comment]
Hi @cmstead ,

there is this function [findScopeTop](https://github.com/cmstead/js-refactor/blob/master/modules/shared/functionScopeUtils.js#L82):
```js
    function findScopeTop(tokens, index) {
        return j.compose(
            j.partial(seekDown, tokens, '{'),
            j.partial(seekUp, tokens, 'function')
        )(index);
    }
```

If I understand it correctly the code is search up for `function` and then down for `{`. I think this is where the issue could be solved. What do you think: Would it work if the code would search for the curly brackets itself (`{ }`) regardless of the function keyword? It would actually change the behavior, but I think in a positive way. Think about `if` statements, `while` loops, variable destructuring and typescript annotations.

In fact the current implementation will break with a `function` keyword too, see this example using destructuring. Extracting the `1` won't work.

![image](https://cloud.githubusercontent.com/assets/13085980/25302756/e1454052-2745-11e7-908d-3a5a2d9a3813.png)

I tried to use VS Code's debugging mode for extensions, but could run any refactoring. It failed:
```
/usr/share/code/code --debugPluginHost=6202 --extensionDevelopmentPath=/home/as/Dev/repository/js-refactor 
Activating extension `cmstead.jsrefactor` failed: {1}.
Activating extension `cmstead.jsrefactor` failed:  undefined
Here is the error stack:  Error: Module "vsCodeFactory" does not exist
```
This is probably a simple mistake. Do I have to do anything else than install the package.json and run `F5` in the directory as described [here](https://code.visualstudio.com/docs/extensions/debugging-extensions)?

What do you think about the logical change for extracting variables?

**Comment by cmstead** [comment]
I will give it a try. The problem I was worried about was if someone is trying to extract a variable inside an object literal:

{
  foo: doSomething(1),
  bar: doSomethingElse(1),
  oneMore: doAnotherThing(1)
}

I think the most reasonable approach is probably going to be just walking the AST (mostly because of the above case). I was trying to avoid that since seeking the location of the selected value inside the tree is a lot more painful.

As far as running the extension in debug mode: you will need to clone the repo, install the dependencies, then open the package as a project in VS Code and run it in debug mode from there.

I appreciate the help. Some of these refactorings have been kind of tricky to even get this far, especially alone.

**Comment by andys8** [comment]
I was quite surprised there is a lot of manual parsing in the code of this extension. Probably parsing the code like linters or [prettier](https://github.com/prettier/prettier) does, is more robust against the lots of possible cases. But I see your point mentioning the selection. 

Could be the better solution to recognize the object case, and skip or handle it.

**Comment by cmstead** [comment]
The benefit prettier and linters have is the either walk the tree starting at the top and just output all the code or log errors as they traverse it. The challenge with writing a refactoring tool is you have to actually reinterpret and rewrite select sections of the code completely, and you may have to work backward instead of forward. On the other hand, people want their code to stay the same other than the one change. It's a challenge, but it's fun. 

Anyway, I'll wipe out my local repo completely and write down all the steps so you have a template to follow. What operating system are you on? I work on a mac and a Windows machine, but I haven't tested Linux if that's what you're using.

**Comment by andys8** [comment]
I understand. If the task to map the current selection or cursor position to the AST is solved, third party code could be used to solve the refactoring tasks. I'm just thinking about the effort people have put in their already in comparable tools that could be used.

Running the extension: Would be great. I'm using Linux Mint, VS Code 1.11.2, npm 4.4.4. I'll try it with a sample extension ;)

**Comment by cmstead** [comment]
Someone built a rename module I looked at but they had to do the same thing I did. If you find existing code that will properly interact with scope, please let me know. It would make my life a lot easier! 

As far as running the extension in debug mode in Linux, I'll run a vm and see if I can figure out what's going wrong. The stack trace helps!

**Comment by cmstead** [comment]
I haven't had a chance to dig into the Linux development issue. (busy week) I do think I have a solution to this issue, though! Stay tuned. : )

**Comment by cmstead** [comment]
I finally got a chance to sit down and finish plowing through a solution. I moved to using estraverse, which took a little migration work, but everything seems to be working as expected.  Version 1.2.0 should fix the arrow function issue you have been encountering.  Now if I could get a little time to look into the linux issue. : /

**Comment by andys8** [comment]
Happy to hear this! Working as expected :) Keep in mind to update the change log that is shown in the store, too.

**Comment by cmstead** [comment]
Oops, thanks.
