### ISSUE TITLE
None of the features work

### ISSUE THREAD

**Issue by AndrewRayCode** [cmstead/js-refactor#57]
Running the contributed command:'cmstead.jsRefactor.extractVariable' failed.
Running the contributed command:'cmstead.jsRefactor.convertToTemplateLiteral' failed.
Running the contributed command:'cmstead.jsRefactor.inlineVariable' failed.
Running the contributed command:'cmstead.jsRefactor.addExport' failed.

etc. I'm in a file ending in ".jsx" if it matters

There is nothing in the "problems", "output" nor "debug console" of vscode

latest of everything

When I put my cursor anywhere in this function:
```
function a() {
  console.log('hi');
}
```
and press cmd+shift+j a, I get

Running the contributed command:'cmstead.jsRefactor.convertToArrowFunction' failed.

**Comment by cmstead** [comment]
Hi, I'll need a little information from you.

First: for your sample, is there any other code in the file? If there is anything that the code parser can't parse, the plugin will fail. 

Second: which operating system are you using? This has been tested in windows 7, windows 10, Linux (Ubuntu 16.04) and Mac.

Thanks for the feedback!

**Comment by rodralme** [comment]
Same error here!
I'm using Linux Mint (Ubuntu 16.04)

**Comment by budajeff** [comment]
The refactorings do not work for me either on Windows 7 and VS Code:

Version 1.20.1
Commit f88bbf9137d24d36d968ea6b2911786bfe103002
Date 2018-02-13T15:34:36.336Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by cmstead** [comment]
Hey all, could one of you do me a favor and post the entire source of a file that is not working? I will use that to debug what is happening.  Thanks so much in advance!

**Comment by rodralme** [comment]
I was trying extract variables on vue code script section.
Same #51 

It was my fault!

**Comment by cmstead** [comment]
@rodralme don't sweat it. On the up-side, I have vue in my sights as well as js embedded in html. I have ideas for how to solve the problem, but I'm still sorting out the details.

To others, I've been wondering if classes in JSX and/or js could be causing problems. I'm currently not managing that at all.

**Comment by cmstead** [comment]
It's looking like this might be a file-type issue, I'm going to act on this assumption and see if I can get any deeper understanding.

**Comment by cmstead** [comment]
I created a set of issues around whether the refactorings will work correctly in different situations.  Please see the following issues:

#61, #62 and #63

Closing this issue since it should be covered in the above issues.

**Comment by trepichio** [comment]
The refactorings do not work for me, only the snippets.
I've tried in both *'js'* and *'vue'* files.

When selecting code and hiting ANY of extension keybinding shortcuts I get something like this: 

`Running the contributed command: 'cmstead.jsRefactor.extractVariable' failed.`

However, If I try to use *any* command through editor context menu or extension menu simply nothing happens! Even no warnings or errors are displayed.

I appreciate if anyone has time to help me find out how to solve this, because I've already checked other related issues and it seems this should be working fine now.
 
My setup:
VSCode Version: 1.55.2
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:37:02.931Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.4.0-72-generic (Ubuntu 20.04)
