### ISSUE TITLE
Refactorings not available for files with "JavaScript React" file type 

### ISSUE THREAD

**Issue by protonmesh** [cmstead/js-refactor#59]
Related to issue #50 but in my case, I have the `.js` file extension associated with the `JavaScript React` file type. 

Refactorings should be enabled not just for `.jsx` extensions, but also those files whose extensions have been associated with `JavaScript React`.

See [Adding a file extension to a language](https://code.visualstudio.com/docs/languages/overview#_adding-a-file-extension-to-a-language)

**Comment by cmstead** [comment]
I didn't realize "Javascript react"  was a file type. I'll look into it.

**Comment by cmstead** [comment]
After looking at the link provided, I don't see anything that would have been missing in the config.  If you are using a custom extension, I will need to know what the extension is in order to provide support.  Please let me know what extensions aside from .js and .jsx would need to be included and I can add them as long as they are common in the community.

**Comment by protonmesh** [comment]
VS code allows arbitrary extensions to be associated with any language id / mode.

My settings has:
```
    "files.associations": {
        "*.js": "javascriptreact"
    },
```

The extension currently doesn't run for files with `javascriptreact` language id/mode. 

Looking at your `package.json`, the `when` conditions may be the issue : 
```
          "when": "resourceLangId == javascript"
```

You will likely need to get `javascriptreact` in there.

**Comment by cmstead** [comment]
Is this a language id you've defined? I want to make sure I'm supporting editor-defined languages and it's not listed in the known ids. https://code.visualstudio.com/docs/languages/identifiers

**Comment by cmstead** [comment]
Just swinging back around. Apparently Vscode added the js react stuff but didn't update so the appropriate references. I'm terribly sorry for all the confusion and back and forth.

**Comment by protonmesh** [comment]
👍No worries. Thanks for tackling this. As you have figured out, `javascriptreact` is a built in language id and the docs are out of date. Happy to test a PR if you can put it up.

**Comment by cmstead** [comment]
Hey, I know this has been sitting for a while. I wanted to provide an update.  I'm working on the react parsing stuff so the refactorings work as expected, so I can't enable the "javascriptreact" file type just yet.  I promise this isn't forgotten, it's just taking time to ensure stability and reliability.

**Comment by johndturn** [comment]
Given my current workflow/projects, all of my javascript files are also mapped to the `javascriptreact` grammar. I'm happy to see that this is a known issue, as I was wondering why none of the refactoring options seemed to be showing up. 

Is there anything that I (or anyone else) might be able to help out with on this issue? This would be great to have support for.

**Comment by cmstead** [comment]
Hey all, I know this has been sitting for a CRAZY long time. It turns out there is a ton I have to do in order to get this working. I have been working on converting over to the Typescript parser which is a lot more permissive in the file format.  Anyway, I just wanted everyone to know solving the deep parsing issues which will lead to good React/ReactJS support has been my top priority work for some time now.

Side note, I have a couple of people who have offered to look into how they might be able to contribute to broader parsing efforts, so I'm hoping things will continue to move forward.  *fingers crossed*

**Comment by cmstead** [comment]
Just a quick update, I can't get Esprima to parse React code, but I believe the TS compiler will.  Marking this dependency for reference:

Depends on: https://github.com/cmstead/js-refactor/issues/54

**Comment by cmstead** [comment]
Latest update, I switched to Espree for parsing.  This supports React, however, it looks like JSX breaks stuff in a pretty nasty way. This has not been forgotten.

**Comment by cmstead** [comment]
For anyone still watching this issue, experimental support has been added for javascriptreact and typescriptreact files.  I am closing this issue and opening new issues for any known problems. Thank you all so much for your patience. Cheers!
