### ISSUE TITLE
Setting to disable editor context menu entries

### ISSUE THREAD

**Issue by Yzrsah** [cmstead/js-refactor#81]
This extension adds 13 context menu entries in JS. The context menu can easily become unusable when it's too large, and require scrolling/not fit on screen.

Please provide a setting to disable editor/context menu entries.

**Comment by cmstead** [comment]
I can see how that could be painful. What if I collapse everything into a single submenu item?

**Comment by cmstead** [comment]
After researching, it looks like there is no way to currently create submenus for the context menu.  There is another item of note which I didn't mention before: menu items are actually handled in the package.json file, not from within executable code. This is problematic because it means I have to either a) turn off the menu items for everyone, or b) leave them in for everyone.

I am going to leave this issue open so I get a reminder to continue researching and see if something comes up over time. I'm sorry I don't have a better answer at the moment.

**Comment by Yzrsah** [comment]
Thank you for the consideration.
We can help to support the open issue [9827](https://github.com/Microsoft/vscode/issues/9827)
js-refactor is a good example of a use case for the nested menu.
I think that MS has been cold on this one in general for UI guideline reasons because they intended to keep the menus simple. But that doesn't work so well with extensions.

**Comment by cmstead** [comment]
I'm really sorry for taking so long to reply. I am closing up shop on JSR, BECAUSE there is a replacement tool. It's still under construction, but it should resolve the issue you are running into.

As an aside, CodeFormer has all of the actions tucked neatly into submenus, which (finally) resolves this issue.

Marketplace:

https://marketplace.visualstudio.com/items?itemName=cmstead.js-codeformer

GitHub:

https://github.com/cmstead/js-codeformer
