### ISSUE TITLE
Rename option not showing

### ISSUE THREAD

**Issue by nmaxcom** [cmstead/js-refactor#89]
I have a keyboard shortcut here:

![image](https://user-images.githubusercontent.com/8936090/55700671-6f7c5680-59d0-11e9-804e-33fa683e9c5d.png)

It's supposed to show all options, but renaming (which if looked up through the palette, JS Refactor has it and it works) doesn't show up in that list:

![image](https://user-images.githubusercontent.com/8936090/55700703-98045080-59d0-11e9-8939-468b5f3184fe.png)

But "manually"...

![image](https://user-images.githubusercontent.com/8936090/55700726-b79b7900-59d0-11e9-9206-3fbbb64668a5.png)

PS: It doesn't appear either in the context menu

**Comment by cmstead** [comment]
I'll take a look into why it's not appearing, but technically, rename is just an alias of the standard VS Code rename function. I'll be writing a rename for JSR in the near future, which will allow users to rename variables in files which aren't supported by the editor rename.

**Comment by nmaxcom** [comment]
Yes. For now, I'd be happy to have rename show, alias or not, for speed's sake.

Thanks.

**Comment by cmstead** [comment]
JS Refactor is no longer supported because I created a ground-up replacement tool. This problem is resolved in the latest version:

GitHub:

https://github.com/cmstead/js-codeformer/releases/tag/v0.15.0

Visual Studio Marketplace:

https://marketplace.visualstudio.com/items?itemName=cmstead.js-codeformer
