### ISSUE TITLE
Does "convert to function declaration" work?

### ISSUE THREAD

**Issue by mvolkmann** [cmstead/js-refactor#94]
I'm trying a very basic use case. I have this arrow function:

```js
const add = (n1, n2) => n1 + n2;
```

I selected that line, opened the Command Palette, and selected "JS Refactor: Convert to Function Declaration". It says "Unable to locate an appropriate function assignment to convert".

**Comment by cmstead** [comment]
I'll test your use case. I haven't encountered the issue you're describing, so it may take some investigating. 

Is there anything else in the file? I've run into issues if/when there is a parse error

**Comment by mvolkmann** [comment]
There are many other functions defined in the file, but it's part of a working app and ESLint likes it.

**Comment by cmstead** [comment]
I got a chance to sit and tinker. I think you found the spot where I paused so I could figure out how to gracefully integrate the conversion to a function expression (from an arrow function) to a function declaration.  If you start with a variable initialized with a function expression, the behavior produces the results you are likely expecting.

I'll throw this in my backlog so I don't keep forgetting about it.  Sorry about the surprise. :-(

**Comment by cmstead** [comment]
I'm really sorry for taking so long to reply. I am closing up shop on JSR, BECAUSE there is a replacement tool. It's still under construction, but it should resolve the issue you are running into.

Marketplace:

https://marketplace.visualstudio.com/items?itemName=cmstead.js-codeformer

GitHub:

https://github.com/cmstead/js-codeformer
